# Generated by Django 4.2.20 on 2025-04-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_user_profile_picture_therapist_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
