# Generated by Django 5.2 on 2025-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'patient'), ('therapist', 'therapist'), ('admin', 'admin')], max_length=20),
        ),
    ]
