# Generated by Django 5.2 on 2025-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='therapist_docs/'),
        ),
    ]
