# Generated by Django 5.2 on 2025-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_therapist_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='autorization_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='province',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
