# Generated by Django 5.2 on 2025-04-29 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_alter_therapist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
