# Generated by Django 5.2 on 2025-04-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_match_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
    ]
