# Generated by Django 5.2 on 2025-05-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_patient_questionnaire_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Stores an array of integers for therapist features.', null=True),
        ),
    ]
