# Generated by Django 4.2.20 on 2025-04-12 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('documents', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireResult', models.JSONField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('CCP', 'CCP'), ('BARIDIMOB', 'BaridiMob')], max_length=20, null=True)),
                ('recomnended_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_patients', to='Authentication.therapist')),
                ('selected_therapists', models.ManyToManyField(related_name='selected_by', to='Authentication.therapist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
