# Generated by Django 4.2.20 on 2025-04-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_therapist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='selected_therapists',
            field=models.ManyToManyField(null=True, related_name='selected_by', to='Authentication.therapist'),
        ),
    ]
